# Generated by Django 2.1.1 on 2019-05-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='lograduro',
            new_name='logradouro',
        ),
    ]
