# Generated by Django 2.1.1 on 2019-06-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190514_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
